const EXPLORER_BASE='https://explorer-studio.genlayer.com/address/';
const SDK={main:'https://esm.sh/genlayer-js@1.0.0?bundle',chains:'https://esm.sh/genlayer-js@1.0.0/chains?bundle',types:'https://esm.sh/genlayer-js@1.0.0/types?bundle'};
const EXPECTED_POLICY="Dependencies must permit commercial use, modification, and redistribution as part of this project without requiring the combined project to disclose its proprietary source code or to be relicensed under the dependency's license.";
const MOCK=new URLSearchParams(location.search).get('mock')==='1';
const STORAGE_KEY='licensegate.contractAddress';
const MOCK_WALLETS=['0x3065E31B1D993d7C0D59E6786844cBa56780B2d3','0x5a52d040581A76e2C032542855D31480f2ea7097','0xADE4533b5C00Fc6c8E44F674213c081D919aaD1D'];
let walletAddress='',busy=false,notice='',error='',txHash='',sdkCache=null,summaryCache=null;

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function short(v=''){return v.length<14?v:`${v.slice(0,6)}…${v.slice(-4)}`;}
function same(a='',b=''){return !!(a&&b&&a.toLowerCase()===b.toLowerCase());}
function validAddress(v=''){return /^0x[a-fA-F0-9]{40}$/.test(String(v).trim());}
function route(){const h=location.hash.replace(/^#\/?/,'');if(h==='evaluate')return{page:'evaluate'};if(h==='registry')return{page:'registry'};const m=h.match(/^dependency\/(\d+)$/);if(m)return{page:'dependency',id:Number(m[1])};return{page:'home'};}
function go(path){location.hash=path.startsWith('/')?`#${path}`:`#/${path}`;}
function addr(v){return `<button class="address-btn mono" data-copy="${esc(v)}" title="${esc(v)}">${esc(short(v))} ⧉</button>`;}
function badge(v){const cls=v==='COMPATIBLE'?'good':v==='INCOMPATIBLE'?'bad':'neutral';return `<span class="badge ${cls}">${esc(v||'NO DECISION')}</span>`;}
function friendly(err){const raw=String(err?.shortMessage??err?.message??err??'Unknown error');const rb=raw.match(/\[rollback\]\s*(.+)/i);if(rb)return rb[1];if(/Only maintainer/i.test(raw))return'Only the contract maintainer can evaluate dependencies.';if(/user rejected|rejected the request|action_rejected/i.test(raw))return'Wallet signature was rejected.';if(/failed to fetch|network|rpc|blocked/i.test(raw))return`Network/RPC error: ${raw}`;return raw.replace(/^Error:\s*/,'');}
function parseResult(raw){let v=raw;if(v&&typeof v==='object'&&typeof v.result==='string')v=v.result;if(typeof v==='string'){const t=v.trim();if(!t)throw new Error('Contract returned an empty response');try{v=JSON.parse(t)}catch{}}return v;}
function parseSummary(raw){const s=String(parseResult(raw));const m=s.match(/^dependency_count=(\d+); last_decision=([^;]*); last_dependency_name=(.*)$/s);if(!m)throw new Error(`Unexpected get_summary response: ${s}`);return{dependency_count:Number(m[1]),last_decision:m[2],last_dependency_name:m[3]};}
function parseDependency(raw,id){const s=String(parseResult(raw));const m=s.match(/^name=(.*?); license=(.*)$/s);if(!m)throw new Error(`Unexpected get_dependency response: ${s}`);return{id,name:m[1],license:m[2]};}
function configuredAddress(){if(MOCK)return'0x1111111111111111111111111111111111111111';const q=new URLSearchParams(location.search).get('contract');if(validAddress(q)){localStorage.setItem(STORAGE_KEY,q);return q;}const hard=window.LICENSEGATE_CONFIG?.contractAddress||'';if(validAddress(hard))return hard;const stored=localStorage.getItem(STORAGE_KEY)||'';return validAddress(stored)?stored:'';}
function saveAddress(v){const a=String(v||'').trim();if(!validAddress(a))throw new Error('Enter a valid 0x contract address.');localStorage.setItem(STORAGE_KEY,a);summaryCache=null;notice=`Using contract ${short(a)}`;error='';render();}
function clearAddress(){localStorage.removeItem(STORAGE_KEY);summaryCache=null;notice='Saved contract address cleared.';render();}

const mockState={wallet:0,summary:{dependency_count:0,last_decision:'',last_dependency_name:''},deps:new Map(),tx:1};
function mockHash(){return'0x'+String(mockState.tx++).padStart(64,'0');}
function classifyMock(text){const t=String(text).toLowerCase();return /(complete corresponding source|same license|must disclose|non-commercial|not for commercial|prohibit commercial|relicense)/.test(t)?'INCOMPATIBLE':'COMPATIBLE';}
function makeMockClient(){return{
 async readContract({functionName,args=[]}){if(functionName==='get_summary')return`dependency_count=${mockState.summary.dependency_count}; last_decision=${mockState.summary.last_decision}; last_dependency_name=${mockState.summary.last_dependency_name}`;if(functionName==='get_dependency'){const d=mockState.deps.get(Number(args[0]));if(!d)throw new Error('[rollback] Dependency not found');return`name=${d.name}; license=${d.license}`;}throw new Error(`Unknown read ${functionName}`);},
 async writeContract({functionName,args=[]}){if(functionName!=='evaluate_dependency')throw new Error(`Unknown write ${functionName}`);if(mockState.wallet!==0)throw new Error('[rollback] Only maintainer');const [name,license]=args;const decision=classifyMock(license);mockState.summary.last_decision=decision;mockState.summary.last_dependency_name=String(name);if(decision==='COMPATIBLE'){const id=++mockState.summary.dependency_count;mockState.deps.set(id,{id,name:String(name),license:String(license)});}return mockHash();},
 async waitForTransactionReceipt(){return{status:'FINALIZED',txExecutionResultName:'FINISHED_WITH_RETURN'};},async connect(){return true;}
};}
async function sdk(){if(MOCK)return null;if(!sdkCache)sdkCache=Promise.all([import(SDK.main),import(SDK.chains),import(SDK.types)]).then(([main,chains,types])=>({main,chains,types}));return sdkCache;}
async function readClient(){if(MOCK)return makeMockClient();const address=configuredAddress();if(!address)throw new Error('Configure the fresh StudioNet contract address first.');const{main}=await sdk();return main.createClient({endpoint:`${location.origin}/api/rpc`});}
async function walletClient(){if(MOCK){walletAddress=MOCK_WALLETS[mockState.wallet];return{client:makeMockClient(),account:walletAddress};}if(!window.ethereum)throw new Error('MetaMask was not detected.');const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const account=accounts?.[0];if(!account)throw new Error('No wallet account selected.');const{main,chains}=await sdk();const client=main.createClient({chain:chains.studionet,account,provider:window.ethereum});await client.connect('studionet');walletAddress=account;return{client,account};}
function executionFailed(r){const n=r?.txExecutionResultName??r?.tx_execution_result_name??r?.executionResultName??r?.execution_result_name??'';return n==='FINISHED_WITH_ERROR'||n==='ERROR';}
async function waitFinalized(hash){const c=await readClient();let last;for(let i=1;i<=45;i++){try{const opt={hash,status:'FINALIZED',fullTransaction:true,interval:10000,retries:1};if(!MOCK){const{types}=await sdk();opt.status=types.TransactionStatus?.FINALIZED??'FINALIZED';}const r=await c.waitForTransactionReceipt(opt);if(executionFailed(r))throw new Error(`Contract reverted (${r.txExecutionResultName||'FINISHED_WITH_ERROR'})`);return r;}catch(e){last=e;const m=String(e?.message??e).toLowerCase();const transient=/429|rate limit|failed to fetch|timeout|pending/.test(m);if(!transient&&i>=3)throw e;await new Promise(r=>setTimeout(r,Math.min(3000+i*1000,12000)));}}throw new Error(`Finalization timeout: ${friendly(last)}`);}
async function submitWrite(functionName,args,progress){const address=configuredAddress()||'0x0000000000000000000000000000000000000001';const{client}=await walletClient();busy=true;error='';notice=progress;txHash='';render();try{const hash=await client.writeContract({address,functionName,args,value:0n});txHash=hash;notice=`Submitted ${short(hash)}. Waiting for FINALIZED…`;render();await waitFinalized(hash);notice='Transaction finalized. Refreshing on-chain state…';return hash;}catch(e){error=friendly(e);notice='';throw e;}finally{busy=false;}}
async function loadSummary(){const c=await readClient();summaryCache=parseSummary(await c.readContract({address:configuredAddress()||'0x0000000000000000000000000000000000000001',functionName:'get_summary',args:[]}));return summaryCache;}
async function loadDependency(id){const c=await readClient();return parseDependency(await c.readContract({address:configuredAddress()||'0x0000000000000000000000000000000000000001',functionName:'get_dependency',args:[Number(id)]}),Number(id));}

function shell(content){const contract=configuredAddress();return`${MOCK?`<div class="mockbar">LOCAL MOCK MODE · Wallet <select id="mock-wallet"><option value="0">Maintainer</option><option value="1">Reader 2</option><option value="2">Reader 3</option></select></div>`:''}<header class="header"><div class="container header-inner"><button class="brand link-btn" data-nav="/"><span class="brand-mark">§</span><span><div class="brand-name">LicenseGate</div><div class="brand-sub">GenLayer StudioNet</div></span></button><nav class="nav"><button data-nav="/">Overview</button><button data-nav="/evaluate">Evaluate</button><button data-nav="/registry">Registry</button></nav><button id="wallet" class="wallet-btn">◈ ${esc(walletAddress?short(walletAddress):'Connect wallet')}</button></div></header>${(notice||error)?`<div class="container notice-wrap">${notice?`<div class="notice">${esc(notice)}${txHash?` <span class="mono">${esc(short(txHash))}</span>`:''}</div>`:''}${error?`<div class="error">${esc(error)}</div>`:''}</div>`:''}${content}<footer class="footer"><div class="container footer-inner"><div>AI decides semantic compatibility. Registry admission remains deterministic.</div>${contract?`<a class="mono" target="_blank" rel="noreferrer" href="${EXPLORER_BASE}${contract}">${short(contract)} ↗</a>`:'<span class="mono">contract not configured</span>'}</div></footer>`;}
function setupCard(){const c=configuredAddress();return`<div class="panel panel-pad setup"><div class="eyebrow">Protocol connection</div><div class="panel-title"><h2>${c?'Fresh contract configured':'Add fresh deployment'}</h2>${c?'<span class="status-dot live">LIVE</span>':'<span class="status-dot">SETUP</span>'}</div><p class="muted small">${c?'Reads and transactions use this StudioNet contract.':'Deploy the approved LicenseCompat.py source, then paste the fresh address here. No rebuild is required for testing.'}</p><div class="lookup-row"><input id="contract-address" class="field mono" placeholder="0x..." value="${esc(c)}"/><button id="save-contract" class="btn-primary">Use contract</button></div>${c?`<div class="contract-actions"><a class="btn-secondary" target="_blank" href="${EXPLORER_BASE}${c}">Explorer ↗</a><button id="clear-contract" class="btn-ghost">Change address</button></div>`:''}</div>`;}
function policyCard(){return`<div class="panel panel-pad"><div class="eyebrow">Immutable deployment baseline</div><h2>Compatibility policy</h2><div class="policy-box">${esc(EXPECTED_POLICY)}</div><p class="muted small">The approved contract stores the deployment policy once. The frontend never changes it.</p></div>`;}
async function home(){let summary=summaryCache;const contract=configuredAddress();if(contract){try{summary=await loadSummary();error='';}catch(e){if(!error)error=friendly(e);}}return shell(`<main><section class="container hero"><div><div class="eyebrow">CONSENSUS-VERIFIED LICENSE ADMISSION</div><h1>Ship dependencies.<br/><span class="gradient-text">Keep policy intact.</span></h1><p class="hero-copy">LicenseGate lets GenLayer validators interpret dependency-license obligations, while the contract deterministically admits only licenses classified as compatible with the fixed project policy.</p><div class="actions"><button class="btn-primary" data-nav="/evaluate">Evaluate dependency →</button><button class="btn-secondary" data-nav="/registry">Browse registry</button></div></div><div class="panel panel-pad hero-panel"><div class="eyebrow">LIVE REGISTRY</div><div class="panel-title"><h2>Dependency admission gate</h2><span class="shield">◈</span></div><div class="metrics"><div class="metric soft"><div class="metric-label">REGISTERED</div><div class="metric-value">${summary?.dependency_count??'—'}</div></div><div class="metric soft"><div class="metric-label">LAST DECISION</div><div class="metric-value compact">${summary?.last_decision?badge(summary.last_decision):'—'}</div></div></div><div class="last-name"><span class="metric-label">LAST EVALUATED</span><strong>${esc(summary?.last_dependency_name||'No evaluation yet')}</strong></div></div></section><section class="container two-col">${setupCard()}${policyCard()}</section><section class="container features"><div class="panel feature"><div class="feature-icon">1</div><h3>Interpret obligations</h3><p>Validators compare the exact license text against the immutable project policy.</p></div><div class="panel feature"><div class="feature-icon">2</div><h3>Fail closed</h3><p>Missing, ambiguous, conflicting, or restrictive rights resolve to INCOMPATIBLE.</p></div><div class="panel feature"><div class="feature-icon">3</div><h3>Admit deterministically</h3><p>Only COMPATIBLE results increment the authoritative dependency registry.</p></div></section></main>`);}
function evaluatePage(){const connected=!!configuredAddress();return shell(`<main class="container page"><button class="page-back" data-nav="/">← Overview</button><div class="page-head"><div><div class="eyebrow">MAINTAINER ACTION</div><h1>Evaluate a dependency</h1><p class="muted">Submit the real dependency license text. GenLayer consensus returns only COMPATIBLE or INCOMPATIBLE.</p></div>${connected?badge(summaryCache?.last_decision||''):'<span class="badge neutral">NO CONTRACT</span>'}</div><div class="evaluate-grid"><div class="panel form-panel"><form id="evaluate-form"><label class="label" for="dep-name">Dependency name</label><input id="dep-name" class="field" maxlength="100" placeholder="e.g. PermissiveLib" required/><div class="form-row"><label class="label" for="license-text">Dependency license text</label><textarea id="license-text" class="field" maxlength="4000" placeholder="Paste the complete license terms to evaluate…" required></textarea><div id="license-count" class="char-count">0/4000</div></div><button class="btn-primary full" ${(!connected||busy)?'disabled':''}>✦ Run consensus compatibility check</button></form><div class="role-warning">Only the contract maintainer can submit evaluations. Any wallet can browse the registry.</div></div>${policyCard()}</div></main>`);}
async function registryPage(){let summary=summaryCache;let deps=[];if(configuredAddress()){try{summary=await loadSummary();const count=summary.dependency_count;const from=Math.max(1,count-19);for(let id=count;id>=from;id--){try{deps.push(await loadDependency(id));}catch{}}}catch(e){error=friendly(e);}}const cards=deps.length?deps.map(d=>`<article class="panel dep-card"><div class="dep-id">#${d.id}</div><h3>${esc(d.name)}</h3><p>${esc(d.license)}</p><button class="btn-secondary" data-nav="/dependency/${d.id}">Open record →</button></article>`).join(''):`<div class="panel empty">No compatible dependency has entered the registry yet.</div>`;return shell(`<main class="container page"><div class="page-head"><div><div class="eyebrow">AUTHORITATIVE STATE</div><h1>Compatible dependency registry</h1><p class="muted">Only dependencies admitted after a COMPATIBLE consensus verdict appear here.</p></div><div class="stat-pill"><span>Registered</span><strong>${summary?.dependency_count??'—'}</strong></div></div><div class="registry-grid">${cards}</div></main>`);}
async function dependencyPage(id){let d;try{d=await loadDependency(id);}catch(e){return shell(`<main class="container page"><button class="page-back" data-nav="/registry">← Registry</button><div class="panel empty">${esc(friendly(e))}</div></main>`);}return shell(`<main class="container page narrow"><button class="page-back" data-nav="/registry">← Registry</button><div class="panel record"><div class="eyebrow">REGISTERED DEPENDENCY #${id}</div><h1>${esc(d.name)}</h1><div class="license-record">${esc(d.license)}</div><div class="record-note">This record exists because the contract admitted the evaluated license into authoritative state.</div></div></main>`);}
async function render(){const r=route();let html;if(r.page==='evaluate')html=evaluatePage();else if(r.page==='registry')html=await registryPage();else if(r.page==='dependency')html=await dependencyPage(r.id);else html=await home();document.getElementById('app').innerHTML=html;bind();}
function bind(){document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>go(el.dataset.nav));document.querySelectorAll('[data-copy]').forEach(el=>el.onclick=async()=>{try{await navigator.clipboard.writeText(el.dataset.copy);notice='Copied to clipboard.';render();}catch{}});const wallet=document.getElementById('wallet');if(wallet)wallet.onclick=async()=>{error='';try{const{account}=await walletClient();notice=`Wallet connected: ${short(account)}`;}catch(e){error=friendly(e);}render();};const sel=document.getElementById('mock-wallet');if(sel){sel.value=String(mockState.wallet);sel.onchange=()=>{mockState.wallet=Number(sel.value);walletAddress=MOCK_WALLETS[mockState.wallet];notice=`Mock wallet switched: ${short(walletAddress)}`;render();};}const ca=document.getElementById('contract-address'),sc=document.getElementById('save-contract');if(sc)sc.onclick=()=>{try{saveAddress(ca.value);}catch(e){error=friendly(e);render();}};const cc=document.getElementById('clear-contract');if(cc)cc.onclick=clearAddress;const lt=document.getElementById('license-text'),lc=document.getElementById('license-count');if(lt)lt.oninput=()=>lc.textContent=`${lt.value.length}/4000`;const form=document.getElementById('evaluate-form');if(form)form.onsubmit=async e=>{e.preventDefault();const name=document.getElementById('dep-name').value.trim(),license=document.getElementById('license-text').value.trim();if(!name||!license)return;try{const before=await loadSummary();await submitWrite('evaluate_dependency',[name,license],'Submitting license for validator consensus…');txHash='';const after=await loadSummary();const registered=after.dependency_count>before.dependency_count;notice=registered?`${after.last_decision}: ${name} entered registry as #${after.dependency_count}.`:`${after.last_decision}: ${name} was not admitted to the registry.`;await render();}catch{}finally{busy=false;}};}
async function init(){if(MOCK){document.documentElement.classList.add('mock');walletAddress=MOCK_WALLETS[0];summaryCache=mockState.summary;}else if(window.ethereum){window.ethereum.on?.('accountsChanged',a=>{walletAddress=a?.[0]||'';render();});window.ethereum.on?.('chainChanged',()=>location.reload());window.ethereum.request({method:'eth_accounts'}).then(a=>{walletAddress=a?.[0]||'';render();}).catch(()=>{});}window.addEventListener('hashchange',()=>{notice='';error='';txHash='';render();});await render();}
init();
