import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root=new URL('../',import.meta.url), dist=new URL('../dist/',import.meta.url);
const EXPECTED_SHA='f1cb33f88b6961b322e5203b363de25aee27f4a67d64a93d2afe203c41fce45d';
await rm(dist,{recursive:true,force:true});
await mkdir(dist,{recursive:true});
for(const f of ['index.html','app.css','app.js','contract-config.js']) await copyFile(new URL(`../${f}`,import.meta.url),new URL(`../dist/${f}`,import.meta.url));
const source=await readFile(new URL('../contracts/LicenseCompat.py',import.meta.url));
const sha=createHash('sha256').update(source).digest('hex');
if(sha!==EXPECTED_SHA) throw new Error(`Contract source changed: ${sha}`);
const cfg=await readFile(new URL('../contract-config.js',import.meta.url),'utf8');
const match=cfg.match(/contractAddress:\s*["']([^"']*)/);
const address=match?.[1]||'';
if(address && !/^0x[a-fA-F0-9]{40}$/.test(address)) throw new Error(`Invalid configured contract address: ${address}`);
const manifest={name:'LicenseGate',network:'GenLayer StudioNet',contract:address||null,contract_source_sha256:sha,built_at:new Date().toISOString()};
await writeFile(new URL('../dist/build-manifest.json',import.meta.url),JSON.stringify(manifest,null,2)+'\n');
console.log('PASS static production build');
console.log(address?`PASS contract ${address}`:'PASS contract address intentionally unset; configure fresh deployment before final submission');
console.log(`PASS source SHA ${sha}`);
